pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'nginx:1.25.4' }
      }
      steps {
        sh 'THIS IS NGINX'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'redis:latest' }
      }
      steps {
        sh 'THIS IS REDIS'
      }
    }
  }
}
